backend:
  name: github
  repo: ssquarephotography/ssquarephotography-website
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
